# Generated by Django 3.1.3 on 2020-11-12 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20201112_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='Click the title to read this article in detail...', max_length=100),
        ),
    ]
